Proposal for documentation extension
I have `pg_restore`'ed from a 64 GB machine to a 32 GB machine and it went seemingly fine. However, there was 1 subtle line in the logs that I overread: 

```
ERROR:  temporary file size exceeds temp_file_limit (30852179kB)
```

This has resulted in skipping index creation on planet_osm_nodes and thus, `nominatim replication` taking literally forever. 
Adding the equal amount of memory to the target SQL instance at least during the restore process is essential.